export const SELECT_FEATURE_LIST_ITEM = 'SELECT_FEATURE_LIST_ITEM';
export const SELECT_FEATURE_FILTER_CLIENT = 'SELECT_FEATURE_FILTER_CLIENT';
export const NAVBACK_FROM_STAGE = 'NAVBACK_FROM_STAGE';

export const REQUEST_FEATURE_CREATE = 'REQUEST_FEATURE_CREATE';
export const RECEIVE_FEATURE_CREATE = 'RECEIVE_FEATURE_CREATE';
export const FAILURE_FEATURE_CREATE = 'FAILURE_FEATURE_CREATE';

export const REQUEST_FEATURE_LIST = 'REQUEST_FEATURE_LIST';
export const RECEIVE_FEATURE_LIST = 'RECEIVE_FEATURE_LIST';
export const FAILURE_FEATURE_LIST = 'FAILURE_FEATURE_LIST';

export const REQUEST_FEATURE_UPDATE = 'REQUEST_FEATURE_UPDATE';
export const RECEIVE_FEATURE_UPDATE = 'RECEIVE_FEATURE_UPDATE';
export const FAILURE_FEATURE_UPDATE = 'FAILURE_FEATURE_UPDATE';

export const SELECT_FEATURE_DELETE = 'SELECT_FEATURE_DELETE';
export const REQUEST_FEATURE_DELETE = 'REQUEST_FEATURE_DELETE';
export const RECEIVE_FEATURE_DELETE = 'RECEIVE_FEATURE_DELETE';
export const FAILURE_FEATURE_DELETE = 'FAILURE_FEATURE_DELETE';


export const CLIENT_ID_MAP = {
  1: 'Client A',
  2: 'Client B',
  3: 'Client C'
};

export const PRODUCT_AREA_ID_MAP = {
  1: 'Policies',
  2: 'Billing',
  3: 'Claims',
  4: 'Reports'
};
