export const SELECT_FEATURE_FILTER_CLIENT = 'SELECT_FEATURE_FILTER_CLIENT';
export const SELECT_FEATURE_CREATE = 'SELECT_FEATURE_CREATE';
export const SELECT_FEATURE_DELETE = 'SELECT_FEATURE_DELETE';

export const REQUEST_FEATURE_LIST = 'REQUEST_FEATURE_LIST';
export const RECEIVE_FEATURE_LIST = 'RECEIVE_FEATURE_LIST';
export const FAILURE_FEATURE_LIST = 'FAILURE_FEATURE_LIST';
