export const SELECT_FEATURE_FILTER_CLIENT = 'SELECT_FEATURE_FILTER_CLIENT';

export const REQUEST_FEATURE_CREATE = 'REQUEST_FEATURE_CREATE';
export const RECEIVE_FEATURE_CREATE = 'RECEIVE_FEATURE_CREATE';
export const FAILURE_FEATURE_CREATE = 'FAILURE_FEATURE_CREATE';

export const SELECT_FEATURE_DELETE = 'SELECT_FEATURE_DELETE';
export const REQUEST_FEATURE_DELETE = 'REQUEST_FEATURE_DELETE';
export const RECEIVE_FEATURE_DELETE = 'RECEIVE_FEATURE_DELETE';
export const FAILURE_FEATURE_DELETE = 'FAILURE_FEATURE_DELETE';

export const REQUEST_FEATURE_LIST = 'REQUEST_FEATURE_LIST';
export const RECEIVE_FEATURE_LIST = 'RECEIVE_FEATURE_LIST';
export const FAILURE_FEATURE_LIST = 'FAILURE_FEATURE_LIST';
