[program:featuring-flask-api]
command=/opt/venv/featuring/bin/gunicorn --chdir /opt/projs/featuring/featuring-flask-api --config=/usr/local/etc/featuring/gunicorn_setting.py featuring.wsgi:app
directory=/opt/projs/featuring/featuring-flask-api/
environment=GUNICORN_PORT='8090',LOGGING_BASEDIR='/var/log/featuring',SECRET_KEY='Tweyrea31kIdicWyff5komvu~Or0A4sVanOkBeçKn6oa9HojoojRyhobyotdemebDalyof)',TOKEN_SECONDS='432000'
user=root
autostart=true
autorestart=true
stopsignal=QUIT
stopasgroup=true
startretries=10000000
redirect_stderr=true
stdout_logfile=/var/log/supervisor/featuring-flask-api.stdout.log
stdout_logfile_maxbytes=1MB
stdout_logfile_backups=10
stdout_capture_maxbytes=1MB
stderr_logfile=/var/log/supervisor/featuring-flask-api.stderr.log
stderr_logfile_maxbytes=1MB
stderr_logfile_backups=10
stderr_capture_maxbytes=1MB
