export const TOKEN_ID = 'authtoken';

export const REQUEST_SESSION_CREATE = 'app/REQUEST_SESSION_CREATE';
export const RECEIVE_SESSION_CREATE = 'app/RECEIVE_SESSION_CREATE';
export const FAILURE_SESSION_CREATE = 'app/FAILURE_SESSION_CREATE';

export const REQUEST_SESSION_DETAIL = 'app/REQUEST_SESSION_DETAIL';
export const RECEIVE_SESSION_DETAIL = 'app/RECEIVE_SESSION_DETAIL';
export const FAILURE_SESSION_DETAIL = 'app/FAILURE_SESSION_DETAIL';
