export const TOKEN_ID = 'authtoken';

export const FLUSH_SESSION = 'FLUSH_SESSION';

export const REQUEST_SESSION_CREATE = 'REQUEST_SESSION_CREATE';
export const RECEIVE_SESSION_CREATE = 'RECEIVE_SESSION_CREATE';
export const FAILURE_SESSION_CREATE = 'FAILURE_SESSION_CREATE';

export const REQUEST_SESSION_DETAIL = 'REQUEST_SESSION_DETAIL';
export const RECEIVE_SESSION_DETAIL = 'RECEIVE_SESSION_DETAIL';
export const FAILURE_SESSION_DETAIL = 'FAILURE_SESSION_DETAIL';
