export const REQUEST_USER_CREATE = 'REQUEST_USER_CREATE';
export const RECEIVE_USER_CREATE = 'RECEIVE_USER_CREATE';
export const FAILURE_USER_CREATE = 'FAILURE_USER_CREATE';

export const REQUEST_USER_LIST = 'REQUEST_USER_LIST';
export const RECEIVE_USER_LIST = 'RECEIVE_USER_LIST';
export const FAILURE_USER_LIST = 'FAILURE_USER_LIST';

export const REQUEST_USER_UPDATE = 'REQUEST_USER_UPDATE';
export const RECEIVE_USER_UPDATE = 'RECEIVE_USER_UPDATE';
export const FAILURE_USER_UPDATE = 'FAILURE_USER_UPDATE';

export const SELECT_USER_DELETE = 'SELECT_USER_DELETE';
export const REQUEST_USER_DELETE = 'REQUEST_USER_DELETE';
export const RECEIVE_USER_DELETE = 'RECEIVE_USER_DELETE';
export const FAILURE_USER_DELETE = 'FAILURE_USER_DELETE';

export const FULLNAME_MIN_LENGTH = 6;
export const FULLNAME_MAX_LENGTH = 100;
