#!/bin/bash
set -e
set -u

HERE=$(echo $(dirname $(readlink -f $0)))
ROOT=$HERE/..

rm -rf $ROOT/build/
rm -rf $ROOT/packaging/
rm -rf $ROOT/debian/{files,tmp,*.log,featuring-flask-api}
rm -rf $ROOT/.coverage
find $ROOT -name '*.pyc' | xargs rm -f
find $ROOT -name '*.cache' -type d | xargs rm -rf
find $ROOT -name 'htmlcov' -type d | xargs rm -rf
