#!/bin/bash
set -e
readonly HERE=$(dirname $(readlink -f $0))

[ -z "$SETTINGS_ENVIRON" ] && export SETTINGS_ENVIRON=featuring.settings.devel
[ -z "$LOGCONFIG_ENVIRON" ] && export LOGCONFIG_ENVIRON=featuring.settings.logconfig.devel
gunicorn --chdir=$HERE/../source --config=$HERE/../gunicorn.py featuring:app
